const en = {
  algoace: 'Algoace',
  appLabel: 'Pupspotter',
  all: 'View All',
  AI: 'Active Ally AI',
  age : 'Age',
  Ai: 'Ai Motivator',
  ask: 'Ask Any Question',
  account: 'Already have an account?',
  accounts: 'Don’t have an account?',
  ages: 'Please select your Age',
  advanced: 'Advanced',
  build: 'Build Muscle',
  body: 'Full Body',
  beginner: 'Beginner',
  builder: 'Motivator',
  bicep: 'Bicep Curl',
  cancel: 'Cancel',
  contact: 'Contact',
  continuewith:'or continue with',
  contactLable: 'Fill in your phone number and location',
  Country: 'Country',
  continuenWithFacebook: 'Continue with Facebook',
  continuenWithGoogle: 'Continue with Google',
  continuenWithApple: 'Continue with Apple',
  continuenWithEmail: 'Continue with Email',
  confirmationCode: 'Confirmation code',
  confirmSignUp: 'Confirm Sign Up',
  continue: 'Continue',
  dietPlan: 'Diet Plan',
  changeLanguage: 'Change language',
  currentpassword: 'Current Password',
  confirmnewpassword: 'Confirm New Password',
  currentpasswords: 'Current password does not match.',
  confirm: 'Confirm',
  contactus: 'Contact Us',
  country: 'Please select your Country',
  city: 'Please select your City',
  california: 'California',
  chat: 'Chat With',
  company: 'Home workout',
  didRecvCode: "Didn't receive code? Resend",
  dob: 'Date of birth',
  description: 'Description',
  detail: 'View Details',
  dip: 'Parallel bar dip',
  dumbbell: 'Dumbbells',
  descriptions: 'Customize your fitness experience to suit your lifestyle and preferences.',
  descriptiontext: 'As a gym motivator, I inspire and guide individuals to reach their fitness goals with encouragement and personalized advice. I create a supportive environment that fosters perseverance and positive lifestyle changes.',
  emailAddress: 'Email Address',
  email: 'Email',
  chooseBodyType:'Choose your body Type',
  experiencedwithfitness: 'How experienced are you with fitness?',
  errorBoundaryLable: 'Something went wrong try again later',
  Equipment: "Do you have Equipment's?",
  equipment: 'No Equipments',
  equipments: 'Please select your Equipment',
  enter: 'Please Enter All Data',
  explore: 'Explore',
  error: 'Error',
  failed: 'Failed to update password:',
  forgotPasswordsmall: 'Forgot Password ?',
  firstName: 'First Name',
  fulltName: 'Full Name',
  forgotPasswordBold: 'Forgot Password',
  forgotChangePasswordLable: 'Forgot password, please reset password, and confirm code via email.',
  forgotPasswordLable: 'We understand you forgot your password, can you please provide your sign up email',
  female: 'Female',
  fit: 'Keep Fit',
  full: 'Full Gym',
  favorite: 'Favorites',
  fitness: 'Please select your Fitness',
  getStarted: 'Get Started',
  gender : 'Gender',
  gpt: 'By Chat GPT',
  goal : 'Muscle Gain',
  gym: 'Garage Gym',
  goals: 'Please select your Goal',
  heightWeight: 'What is your height And Weight?',
  home: 'Home',
  howOldAreYou: 'How Old Are You?',
  heights: 'Please select your Height',
  height :'Height',
  Knee: 'Knee touch',
  invalid: 'Invalid Email',
  intermediate: 'Intermediate',
  language: 'Language',
  listIsEmpty: 'List is empty',
  lose: 'Lose Weight',
  login: 'Login',
  logout: 'Logout',
  logouts: 'Are You Sure You Want to logout?',
  lastName: 'Last Name',
  Location: 'Choose Your Location?',
  lunge: 'Lunge',
  level : 'Level',
  male: 'Male',
  mainGoal: 'What is  your goal?',
  muscle: 'Build Muscle',
  motivator: 'AI Motivator',
  motivators: 'Motivators',
  motivation: 'Workout Motivation',
  mail: 'Please verify your Email',
  must: 'Password must be at least 6 characters long, and include uppercase, lowercase, number, and special character.',
  MESSAGES: {
    emailRequired: 'Email is required',
    emailInvalid: 'Email is invalid',
    firstNameRequired: 'First Name is required',
    firstNameInvalid: 'First Name is invalid',
    firstNameLessLength: 'First Name should be less then 30 characters',
    firstNameShort: 'First name too short',
    lastNameLessLength: 'Last Name should be less then 30 characters',
    lastNameShort: 'Last name too short',
    lastNameRequired: 'Last Name is required',
    lastNameInvalid: 'Last Name is invalid',
    otpLength: 'OTP must be exactly 6 characters',
    otpRequired: 'OTP required',
    passwordInvalid: 'Password is invalid',
    passwordRequired: 'Password is required',
    passwordNotMatch: 'Password does not match',
    passwordLength: 'Invalid password it should on UpperCase, lowerCase, letter and one number',
  },
  newPassword: 'New Password',
  newPasswords: 'New passwords do not match.',
  name: 'John Smith',
  names : 'Name',
  new: 'Confirm New Password',
  no: 'No',
  nextStep: 'Next Step',
  notification: 'Notification',
  oops: 'Oops!',
  Overhead: 'Overhead press',
  password: 'Password',
  profile: 'Profile',
  phoneNumber: 'Phone Number',
  popular: 'Popular',
  privacy: 'Privacy Policy',
  passwords: 'Change Password',
  passwordupdated: 'Password updated successfully.',
  pushup: 'Push-up',
  resendCode: 'Resend code',
  resetPassword: 'Reset Password',
  reEnterPassword: 'Re-enter new password',
  signUp: 'Sign Up',
  submit: 'Submit',
  selectDate: 'Select Date',
  state: 'State',
  selectCriteria: 'Select your criteria',
  signInLabel: 'Fill out your email address and password',
  signUpLabel: 'Fill in your personal information',
  save: 'Save',
  setting: 'Settings',
  start: 'Lets Start workout!',
  searchText: 'Search here...',
  selectAge: 'Select Age',
  selectHeight: 'Select Height',
  selectWeight: 'Select Weight',
  selectCountry: 'Select Country',
  selectCity: 'Select City',
  selectState: 'State (Optional)',
  squat: 'Squat',
  select: 'Please select your Workout',
  success: 'Success',
  tapToProceed: 'Tap to proceed',
  tryAgain: 'Try again',
  title: 'Your Fitness, Your Way',
  Times: 'Times / Week',
  terms : 'Terms & Conditions',
  termOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termTwo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termThree: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termFour: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ',
  update: 'Update',
  verificationSentCode: 'Verification code has been sent to your email address',
  Verification: 'Verification',
  valid: 'Please enter a valid email address with a proper format.',
  video: 'Videos',
  validation: 'Validation',
  welcomeBack: 'Welcome Back',
  Whatisyourname: 'What is your name?',
  Whatisyourgender: 'What is your Gender?',
  workout: 'How often do you want to workout?',
  Welcome: 'Welcome',
  weight: 'Your Weight',
  weights : 'Weight',
  workouts : 'Workout Count',
  walking: 'Walking',
  weightss: 'Please select your Weight',
  weak: 'Weak Password',
  yes: 'Yes',
};

export default en;
export type Translations = typeof en;
