import {Translations} from './en';

const fr: Translations = {
  algoace: 'Algoace',
  appLabel: 'Pupspotter',
  all: 'Voir tout',
  AI: 'Allié actif AI',
  age: 'Âge',
  Ai: 'Motivateur AI',
  ask: 'Poser une question',
  account: 'Vous avez déjà un compte ?',
  accounts: "Vous n'avez pas de compte ?",
  ages: 'Veuillez sélectionner votre âge',
  advanced: 'Avancé',
  build: 'Construire du muscle',
  body: 'Corps complet',
  beginner: 'Débutant',
  builder: 'Motivateur',
  bicep: 'Flexion des biceps',
  Country: 'Pays',
  contact: 'Contact',
  continuewith:'ou continuer avec',
  continuenWithFacebook: 'Continuer avec Facebook',
  continuenWithGoogle: 'Continuer avec Google',
  continuenWithApple: 'Continuer avec Apple',
  continuenWithEmail: "Continuer avec l'email",
  continue: 'Continuer',
  confirmationCode: 'Code de confirmation',
  confirmSignUp: "Confirmer l'inscription",
  changeLanguage: 'Changer de langue',
  cancel: 'Annuler',
  contactLable: 'Remplissez votre numéro de téléphone et votre emplacement',
  currentpassword: 'Mot de passe actuel',
  currentpasswords: 'Le mot de passe actuel ne correspond pas.',
  confirmnewpassword: 'Confirmer le nouveau mot de passe',
  confirm: 'Confirmer',
  contactus: 'Nous contacter',
  country: 'Veuillez sélectionner votre pays',
  city: 'Veuillez sélectionner votre ville',
  california: 'Californie',
  chat: 'Discuter avec',
  company: 'Par Active Ally',
  dob: 'Date de naissance',
  didRecvCode: "Vous n'avez pas reçu le code? Resend",
  description: 'Description',
  detail: 'Voir les détails',
  dip: 'Dips sur barre parallèle',
  dumbbell: 'Haltères',
  descriptions: "Salut, je suis votre coach personnel propulsé par l'IA.",
  descriptiontext:
    "En tant que motivateur de gym, j'inspire et guide les individus pour atteindre leurs objectifs de fitness avec encouragement et conseils personnalisés. Je crée un environnement de soutien qui favorise la persévérance et les changements de mode de vie positifs.",
  email: 'Email',
  emailAddress: 'Adresse email',
  errorBoundaryLable: "Quelque chose s'est mal passé, essayez à nouveau plus tard",
  experiencedwithfitness: 'Quelle est votre expérience en matière de fitness ?',
  Equipment: 'Quels équipements avez-vous ?',
  equipment: "Pas d'équipement",
  equipments: 'Veuillez sélectionner votre équipement',
  enter: 'Veuillez entrer toutes les données',
  explore: 'Explorer',
  error: 'Erreur',
  failed: 'Échec de la mise à jour du mot de passe :',
  firstName: 'Prénom',
  forgotPasswordsmall: 'Mot de passe oublié?',
  forgotPasswordBold: 'Mot de passe oublié',
  forgotChangePasswordLable:
    'Mot de passe oublié, veuillez réinitialiser le mot de passe et confirmer le code via email.',
  forgotPasswordLable:
    "Nous comprenons que vous avez oublié votre mot de passe, pouvez-vous s'il vous plaît fournir votre email d'inscription",
  fulltName: 'Nom complet',
  female: 'Femme',
  fit: 'Rester en forme',
  full: 'Salle de sport complète',
  favorite: 'Favoris',
  fitness: 'Veuillez sélectionner votre niveau de forme physique',
  getStarted: 'Commencer',
  gender: 'Genre',
  gpt: 'Par Chat GPT',
  goal: 'Gain musculaire',
  gym: 'Salle de sport à domicile',
  goals: 'Veuillez sélectionner votre objectif',
  home: 'Accueil',
  heightWeight: 'Quelle est votre taille et poids ?',
  howOldAreYou: 'Quel âge avez-vous ?',
  heights: 'Veuillez sélectionner votre taille',
  height: 'Taille',
  Knee: 'Toucher du genou',
  invalid: 'E-mail invalide',
  intermediate: 'Intermédiaire',
  language: "Langue",
  listIsEmpty: 'La liste est vide',
  login: 'Connexion',
  logout: 'Se déconnecter',
  lastName: 'Nom de famille',
  lose: 'Perdre du poids',
  logouts: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  Location: 'Choisissez votre emplacement',
  lunge: 'Fente',
  level: 'Niveau',
  male: 'Homme',
  mainGoal: 'Quel est votre objectif principal ?',
  muscle: 'Développer les muscles',
  motivator: 'Motivateur AI',
  motivators: 'Motivateurs',
  motivation: 'Motivation à l\'entraînement',
  mail: 'Veuillez vérifier votre e-mail',
  must: 'Le mot de passe doit comporter au moins 6 caractères et inclure des majuscules, des minuscules, des chiffres et des caractères spéciaux.',
  MESSAGES: {
    emailRequired: "L'email est obligatoire",
    emailInvalid: "L'email est invalide",
    firstNameRequired: 'Le prénom est obligatoire',
    firstNameLessLength: 'Le prénom doit comporter moins de 30 caractères',
    firstNameInvalid: 'Le prénom est invalide',
    firstNameShort: 'Prénom trop court',
    lastNameShort: 'Nom de famille trop court',
    lastNameRequired: 'Le nom de famille est obligatoire',
    lastNameLessLength: 'Le nom de famille doit comporter moins de 30 caractères',
    lastNameInvalid: 'Le nom de famille est invalide',
    otpLength: 'Le code OTP doit comporter exactement 6 caractères',
    otpRequired: 'Le code OTP est obligatoire',
    passwordInvalid: 'Le mot de passe est invalide',
    passwordRequired: 'Le mot de passe est obligatoire',
    passwordNotMatch: 'Les mots de passe ne correspondent pas',
    passwordLength: 'Mot de passe invalide, il doit contenir une majuscule, une minuscule, une lettre et un chiffre',
  },
  no: 'Non',
  newPassword: 'Nouveau mot de passe',
  newPasswords: 'Les nouveaux mots de passe ne correspondent pas.',
  name: 'John Smith',
  names: 'Nom',
  new: 'Confirmer le nouveau mot de passe',
  nextStep: 'Étape suivante',
  notification: 'Notification',
  oops: 'Oups !',
  Overhead: 'Développé militaire',
  phoneNumber: 'Numéro de téléphone',
  profile: 'Profil',
  password: 'Mot de passe',
  popular: 'Populaire',
  privacy: 'Politique de confidentialité',
  passwords: 'Changer le mot de passe',
  passwordupdated: 'Mot de passe mis à jour avec succès.',
  pushup: 'Pompes',
  resendCode: 'Renvoyer le code',
  resetPassword: 'Réinitialiser le mot de passe',
  reEnterPassword: 'Saisissez à nouveau le nouveau mot de passe',
  selectDate: 'Sélectionner la date',
  state: 'État',
  signUp: "S'inscrire",
  submit: 'Soumettre',
  selectCriteria: 'Sélectionnez vos critères',
  signInLabel: 'Remplissez votre adresse email et votre mot de passe',
  signUpLabel: 'Remplissez vos informations personnelles',
  save: 'Enregistrer',
  setting: 'Paramètres',
  start: 'Commençons l\'entraînement !',
  searchText: 'Cherchez ici...',
  selectAge: 'Sélectionner l\'âge',
  selectHeight: 'Sélectionner la taille',
  selectWeight: 'Sélectionner le poids',
  selectCountry: 'Sélectionner le pays',
  selectCity: 'Sélectionner la ville',
  selectState: 'État (Optionnel)',
  squat: 'Squat',
  select: 'Veuillez sélectionner votre entraînement',
  success: 'Succès',
  tapToProceed: 'Appuyez pour continuer',
  tryAgain: 'Réessayer',
  title: 'Transformez Votre Vie Pour Le Meilleur',
  Times: 'Fois / Semaine',
  terms: 'Termes et Conditions',
  termOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termTwo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termThree: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termFour: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ',
  update: 'Mettre à jour',
  verificationSentCode: 'Le code de vérification a été envoyé à votre adresse e-mail',
  Verification: 'Vérification',
  valid: 'Veuillez entrer une adresse e-mail valide avec un format approprié.',
  video: 'Vidéos',
  validation: 'Validation',
  welcomeBack: 'Bon retour',
  Whatisyourname: 'Quel est votre nom ?',
  Whatisyourgender: 'Quel est votre genre ?',
  workout: 'À quelle fréquence voulez-vous vous entraîner ?',
  Welcome: 'Bienvenue',
  weight: 'Votre poids',
  weights: 'Poids',
  workouts: 'Nombre d\'entraînements',
  walking: 'Marche',
  weightss: 'Veuillez sélectionner votre poids',
  weak: 'Mot de passe faible',
  yes: 'Oui',
};

export default fr;
