import {Translations} from './en';

const ur: Translations = {
  algoace: 'Algoace',
  appLabel: 'پپ سپاٹر',
  all: 'تمام دیکھیں',
  AI: 'ایکٹیو اتحادی اے آئی',
  age: 'عمر',
  Ai: 'اے آئی محرک',
  ask: 'کوئی بھی سوال پوچھیں',
  account: 'کیا آپ کے پاس پہلے سے ایک اکاؤنٹ ہے؟',
  accounts: 'کیا آپ کے پاس اکاؤنٹ نہیں ہے؟',
  ages: 'براہ کرم اپنی عمر منتخب کریں',
  advanced: 'ایڈوانسڈ',
  build: 'پٹھے بنائیں',
  body: 'مکمل جسم',
  beginner: 'ابتدائی',
  builder: 'محرک',
  bicep: 'بائسپس کرل',
  cancel: 'منسوخ کریں',
  contact: 'رابطہ کریں',
  continuewith:'یا جاری رکھیں ساتھ',
  contactLable: 'اپنا فون نمبر اور مقام درج کریں',
  Country: 'ملک',
  continuenWithFacebook: 'فیس بک کے ساتھ جاری رکھیں',
  continuenWithGoogle: 'گوگل کے ساتھ جاری رکھیں',
  continuenWithApple: 'ایپل کے ساتھ جاری رکھیں',
  continuenWithEmail: 'ای میل کے ساتھ جاری رکھیں',
  confirmationCode: 'تصدیقی کوڈ',
  confirmSignUp: 'سائن اپ کی تصدیق کریں',
  continue: 'جاری رکھیں',
  changeLanguage: 'زبان تبدیل کریں',
  currentpassword: 'موجودہ پاس ورڈ',
  currentpasswords: 'موجودہ پاس ورڈ میل نہیں کھاتا۔',
  confirmnewpassword: 'نیا پاس ورڈ کی تصدیق کریں',
  confirm: 'تصدیق کریں',
  contactus: 'ہم سے رابطہ کریں',
  country: 'براہ کرم اپنا ملک منتخب کریں',
  city: 'براہ کرم اپنا شہر منتخب کریں',
  california: 'کیلیفورنیا',
  chat: 'چیٹ کریں',
  company: 'بذریعہ ایکٹیو اتحادی',
  didRecvCode: 'کوڈ موصول نہیں ہوا؟ دوبارہ بھیجیں',
  dob: 'پیدائش کی تاریخ',
  description: 'تفصیل',
  detail: 'تفصیلات دیکھیں',
  dip: 'متوازی بار ڈپ',
  dumbbell: 'ڈمبلز',
  descriptions: 'ارے، میں آپ کا ذاتی ٹرینر ہوں، اے آئی سے چلنے والا۔',
  descriptiontext:
    'بطور جم موٹیویٹر، میں افراد کو ان کے فٹنس اہداف تک پہنچنے کے لیے حوصلہ افزائی اور ذاتی مشورے فراہم کرتا ہوں۔ میں ایک معاون ماحول بناتا ہوں جو استقامت اور مثبت طرز زندگی میں تبدیلیوں کو فروغ دیتا ہے۔',
  emailAddress: 'ای میل ایڈریس',
  email: 'ای میل',
  experiencedwithfitness: 'آپ کا فٹنس کے ساتھ کتنا تجربہ ہے؟',
  errorBoundaryLable: 'کچھ غلط ہو گیا، براہ کرم بعد میں دوبارہ کوشش کریں',
  Equipment: 'آپ کے پاس کون سا سامان ہے؟',
  equipment: 'کوئی سامان نہیں',
  equipments: 'براہ کرم اپنا سامان منتخب کریں',
  enter: 'براہ کرم تمام ڈیٹا درج کریں',
  explore: 'دریافت کریں',
  error: 'غلطی',
  failed: 'پاس ورڈ کو اپ ڈیٹ کرنے میں ناکامی:',
  forgotPasswordsmall: 'پاس ورڈ بھول گئے؟',
  firstName: 'پہلا نام',
  fulltName: 'پورا نام',
  forgotPasswordBold: 'پاس ورڈ بھول گئے',
  forgotChangePasswordLable: 'پاس ورڈ بھول گئے، براہ کرم پاس ورڈ ری سیٹ کریں، اور ای میل کے ذریعے کوڈ کی تصدیق کریں۔',
  forgotPasswordLable: 'ہم سمجھتے ہیں کہ آپ نے اپنا پاس ورڈ بھول گئے ہیں، براہ کرم اپنا سائن اپ ای میل فراہم کریں',
  female: 'خاتون',
  fit: 'فٹ رہیں',
  full: 'مکمل جم',
  favorite: 'پسندیدہ',
  fitness: 'براہ کرم اپنی فٹنس کا انتخاب کریں',
  getStarted: 'شروع کریں',
  gender: 'صنف',
  gpt: 'بذریعہ چیٹ جی پی ٹی',
  goal: 'پٹھوں کا اضافہ',
  gym: 'گیراج جم',
  goals: 'براہ کرم اپنا مقصد منتخب کریں',
  heightWeight: 'آپ کی اونچائی اور وزن کیا ہے؟',
  home: 'گھر',
  howOldAreYou: 'آپ کی عمر کیا ہے؟',
  heights: 'براہ کرم اپنی اونچائی منتخب کریں',
  height: 'اونچائی',
  Knee: 'گھٹنے کا ٹچ',
  invalid: 'غلط ای میل',
  intermediate: 'درمیانہ',
  language: "زبان",
  listIsEmpty: 'فہرست خالی ہے',
  lose: 'وزن کم کریں',
  login: 'لاگ ان',
  logout: 'لاگ آؤٹ',
  logouts: 'کیا آپ واقعی لاگ آؤٹ ہونا چاہتے ہیں؟',
  lastName: 'آخری نام',
  Location: 'اپنا مقام منتخب کریں',
  lunge: 'لنج',
  level: 'سطح',
  male: 'مرد',
  mainGoal: 'آپ کا بنیادی مقصد کیا ہے؟',
  muscle: 'پٹھے بنائیں',
  motivator: 'اے آئی موٹیویٹر',
  motivators: 'موٹیویٹرز',
  motivation: 'ورزش کی حوصلہ افزائی',
  mail: 'براہ کرم اپنا ای میل تصدیق کریں',
  must: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے، اور اس میں بڑے، چھوٹے، نمبر اور خصوصی کردار شامل ہوں۔',
  MESSAGES: {
    emailRequired: 'ای میل ضروری ہے',
    emailInvalid: 'ای میل درست نہیں ہے',
    firstNameRequired: 'پہلا نام ضروری ہے',
    firstNameInvalid: 'پہلا نام درست نہیں ہے',
    firstNameLessLength: 'پہلا نام 30 حروف سے کم ہونا چاہئے',
    firstNameShort: 'پہلا نام بہت مختصر ہے',
    lastNameLessLength: 'آخری نام 30 حروف سے کم ہونا چاہئے',
    lastNameShort: 'آخری نام بہت مختصر ہے',
    lastNameRequired: 'آخری نام ضروری ہے',
    lastNameInvalid: 'آخری نام درست نہیں ہے',
    otpLength: 'OTP کو بالکل 6 حروف پر مشتمل ہونا چاہئے',
    otpRequired: 'OTP ضروری ہے',
    passwordInvalid: 'پاس ورڈ درست نہیں ہے',
    passwordRequired: 'پاس ورڈ ضروری ہے',
    passwordNotMatch: 'پاس ورڈ میچ نہیں کرتا',
    passwordLength: 'غلط پاس ورڈ، یہ ایک بڑے حرف، چھوٹے حرف، ایک حرف اور ایک نمبر پر مشتمل ہونا چاہئے',
  },
  newPassword: 'نیا پاس ورڈ',
  newPasswords: 'نئے پاس ورڈز میل نہیں کھاتے۔',
  name: 'جان سمتھ',
  names: 'نام',
  new: 'نیا پاس ورڈ کی تصدیق کریں',
  no: 'نہیں',
  nextStep: 'اگلا قدم',
  notification: 'نوٹیفکیشن',
  oops: 'اوپس!',
  Overhead: 'اوور ہیڈ پریس',
  password: 'پاس ورڈ',
  profile: 'پروفائل',
  phoneNumber: 'فون نمبر',
  popular: 'مشہور',
  privacy: 'رازداری کی پالیسی',
  passwords: 'پاس ورڈ تبدیل کریں',
  passwordupdated: 'پاس ورڈ کامیابی کے ساتھ اپ ڈیٹ کر دیا گیا۔',
  pushup: 'پش اپ',
  resendCode: 'کوڈ دوبارہ بھیجیں',
  resetPassword: 'پاس ورڈ دوبارہ سیٹ کریں',
  reEnterPassword: 'نیا پاس ورڈ دوبارہ درج کریں',
  signUp: 'سائن اپ کریں',
  submit: 'جمع کریں',
  selectDate: 'تاریخ منتخب کریں',
  state: 'ریاست',
  selectCriteria: 'اپنے معیار کا انتخاب کریں',
  signInLabel: 'اپنا ای میل ایڈریس اور پاس ورڈ درج کریں',
  signUpLabel: 'اپنی ذاتی معلومات درج کریں',
  save: 'محفوظ کریں',
  setting: 'سیٹنگز',
  start: 'ورزش شروع کرتے ہیں!',
  searchText: 'یہاں تلاش کریں...',
  selectAge: 'عمر منتخب کریں',
  selectHeight: 'اونچائی منتخب کریں',
  selectWeight: 'وزن منتخب کریں',
  selectCountry: 'ملک منتخب کریں',
  selectCity: 'شہر منتخب کریں',
  selectState: 'ریاست (اختیاری)',
  squat: 'اسکواٹ',
  select: 'براہ کرم اپنی ورزش منتخب کریں',
  success: 'کامیابی',
  tapToProceed: 'جاری رکھنے کے لئے ٹیپ کریں',
  tryAgain: 'دوبارہ کوشش کریں',
  title: 'اپنی زندگی کو بہتر کے لیے تبدیل کریں',
  Times: 'بار / ہفتہ',
  terms: 'شرائط و ضوابط',
  termOne: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termTwo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termThree: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  termFour: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ',
  update: 'اپ ڈیٹ کریں',
  verificationSentCode: 'تصدیقی کوڈ آپ کے ای میل ایڈریس پر بھیج دیا گیا ہے',
  Verification: 'تصدیق',
  valid: 'براہ کرم ایک درست ای میل ایڈریس درج کریں جو مناسب فارمیٹ میں ہو۔',
  video: 'ویڈیوز',
  validation: 'تصدیق',
  welcomeBack: 'خوش آمدید',
  Whatisyourname: 'آپ کا نام کیا ہے؟',
  Whatisyourgender: 'آپ کی جنس کیا ہے؟',
  workout: 'آپ کتنی بار ورزش کرنا چاہتے ہیں؟',
  Welcome: 'خوش آمدید',
  weight: 'آپ کا وزن',
  weights: 'وزن',
  workouts: 'ورزشوں کی تعداد',
  walking: 'چلنا',
  weightss: 'براہ کرم اپنا وزن منتخب کریں',
  weak: 'کمزور پاس ورڈ',
  yes: 'ہاں',
};

export default ur;
